/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIdRouteImport } from './routes/tracking.$id'
import { Route as PetsIdRouteImport } from './routes/pets.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as BlogIdRouteImport } from './routes/blog.$id'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIdRoute = TrackingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TrackingRoute,
} as any)
const PetsIdRoute = PetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PetsRoute,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/blog': typeof BlogRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/pets': typeof PetsRouteWithChildren
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/blog/$id': typeof BlogIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pets/$id': typeof PetsIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/blog': typeof BlogRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/pets': typeof PetsRouteWithChildren
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/blog/$id': typeof BlogIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pets/$id': typeof PetsIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/blog': typeof BlogRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/pets': typeof PetsRouteWithChildren
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/blog/$id': typeof BlogIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pets/$id': typeof PetsIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/blog'
    | '/community'
    | '/contact'
    | '/contests'
    | '/dashboard'
    | '/favorites'
    | '/insurance'
    | '/login'
    | '/match'
    | '/pets'
    | '/referrals'
    | '/register'
    | '/tracking'
    | '/blog/$id'
    | '/checkout/$id'
    | '/pets/$id'
    | '/tracking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/blog'
    | '/community'
    | '/contact'
    | '/contests'
    | '/dashboard'
    | '/favorites'
    | '/insurance'
    | '/login'
    | '/match'
    | '/pets'
    | '/referrals'
    | '/register'
    | '/tracking'
    | '/blog/$id'
    | '/checkout/$id'
    | '/pets/$id'
    | '/tracking/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/blog'
    | '/community'
    | '/contact'
    | '/contests'
    | '/dashboard'
    | '/favorites'
    | '/insurance'
    | '/login'
    | '/match'
    | '/pets'
    | '/referrals'
    | '/register'
    | '/tracking'
    | '/blog/$id'
    | '/checkout/$id'
    | '/pets/$id'
    | '/tracking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  BlogRoute: typeof BlogRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  ContestsRoute: typeof ContestsRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  InsuranceRoute: typeof InsuranceRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  PetsRoute: typeof PetsRouteWithChildren
  ReferralsRoute: typeof ReferralsRoute
  RegisterRoute: typeof RegisterRoute
  TrackingRoute: typeof TrackingRouteWithChildren
  CheckoutIdRoute: typeof CheckoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$id': {
      id: '/tracking/$id'
      path: '/$id'
      fullPath: '/tracking/$id'
      preLoaderRoute: typeof TrackingIdRouteImport
      parentRoute: typeof TrackingRoute
    }
    '/pets/$id': {
      id: '/pets/$id'
      path: '/$id'
      fullPath: '/pets/$id'
      preLoaderRoute: typeof PetsIdRouteImport
      parentRoute: typeof PetsRoute
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PetsRouteChildren {
  PetsIdRoute: typeof PetsIdRoute
}

const PetsRouteChildren: PetsRouteChildren = {
  PetsIdRoute: PetsIdRoute,
}

const PetsRouteWithChildren = PetsRoute._addFileChildren(PetsRouteChildren)

interface TrackingRouteChildren {
  TrackingIdRoute: typeof TrackingIdRoute
}

const TrackingRouteChildren: TrackingRouteChildren = {
  TrackingIdRoute: TrackingIdRoute,
}

const TrackingRouteWithChildren = TrackingRoute._addFileChildren(
  TrackingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  BlogRoute: BlogRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  ContestsRoute: ContestsRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  InsuranceRoute: InsuranceRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  PetsRoute: PetsRouteWithChildren,
  ReferralsRoute: ReferralsRoute,
  RegisterRoute: RegisterRoute,
  TrackingRoute: TrackingRouteWithChildren,
  CheckoutIdRoute: CheckoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
